# do not edit: auto-generated file, via `gencurrencies()`

const AED = Currency("AED", "UAE Dirham", "د.إ", 784, 2)
const AFN = Currency("AFN", "Afghani", "", 971, 2)
const ALL = Currency("ALL", "Lek", "", 8, 2)
const AMD = Currency("AMD", "Armenian Dram", "", 51, 2)
const ANG = Currency("ANG", "Netherlands Antillean Guilder", "ƒ", 532, 2)
const AOA = Currency("AOA", "Kwanza", "", 973, 2)
const ARS = Currency("ARS", "Argentine Peso", "\$", 32, 2)
const AUD = Currency("AUD", "Australian Dollar", "A\$", 36, 2)
const AWG = Currency("AWG", "Aruban Florin", "", 533, 2)
const AZN = Currency("AZN", "Azerbaijan Manat", "", 944, 2)
const BAM = Currency("BAM", "Convertible Mark", "", 977, 2)
const BBD = Currency("BBD", "Barbados Dollar", "", 52, 2)
const BDT = Currency("BDT", "Taka", "", 50, 2)
const BGN = Currency("BGN", "Bulgarian Lev", "", 975, 2)
const BHD = Currency("BHD", "Bahraini Dinar", "", 48, 3)
const BIF = Currency("BIF", "Burundi Franc", "", 108, 0)
const BMD = Currency("BMD", "Bermudian Dollar", "", 60, 2)
const BND = Currency("BND", "Brunei Dollar", "", 96, 2)
const BOB = Currency("BOB", "Boliviano", "", 68, 2)
const BOV = Currency("BOV", "Mvdol", "", 984, 2)
const BRL = Currency("BRL", "Brazilian Real", "R\$", 986, 2)
const BSD = Currency("BSD", "Bahamian Dollar", "B\$", 44, 2)
const BTN = Currency("BTN", "Ngultrum", "", 64, 2)
const BWP = Currency("BWP", "Pula", "", 72, 2)
const BYN = Currency("BYN", "Belarusian Ruble", "", 933, 2)
const BZD = Currency("BZD", "Belize Dollar", "", 84, 2)
const CAD = Currency("CAD", "Canadian Dollar", "\$", 124, 2)
const CDF = Currency("CDF", "Congolese Franc", "", 976, 2)
const CHE = Currency("CHE", "WIR Euro", "", 947, 2)
const CHF = Currency("CHF", "Swiss Franc", "CHF", 756, 2)
const CHW = Currency("CHW", "WIR Franc", "", 948, 2)
const CLF = Currency("CLF", "Unidad de Fomento", "", 990, 4)
const CLP = Currency("CLP", "Chilean Peso", "\$", 152, 0)
const CNY = Currency("CNY", "Yuan Renminbi", "¥", 156, 2)
const COP = Currency("COP", "Colombian Peso", "\$", 170, 2)
const COU = Currency("COU", "Unidad de Valor Real", "", 970, 2)
const CRC = Currency("CRC", "Costa Rican Colon", "", 188, 2)
const CUC = Currency("CUC", "Peso Convertible", "", 931, 2)
const CUP = Currency("CUP", "Cuban Peso", "", 192, 2)
const CVE = Currency("CVE", "Cabo Verde Escudo", "", 132, 2)
const CZK = Currency("CZK", "Czech Koruna", "Kč", 203, 2)
const DJF = Currency("DJF", "Djibouti Franc", "", 262, 0)
const DKK = Currency("DKK", "Danish Krone", "kr", 208, 2)
const DOP = Currency("DOP", "Dominican Peso", "", 214, 2)
const DZD = Currency("DZD", "Algerian Dinar", "", 12, 2)
const EGP = Currency("EGP", "Egyptian Pound", "", 818, 2)
const ERN = Currency("ERN", "Nakfa", "", 232, 2)
const ETB = Currency("ETB", "Ethiopian Birr", "", 230, 2)
const EUR = Currency("EUR", "Euro", "€", 978, 2)
const FJD = Currency("FJD", "Fiji Dollar", "FJ\$", 242, 2)
const FKP = Currency("FKP", "Falkland Islands Pound", "", 238, 2)
const GBP = Currency("GBP", "Pound Sterling", "£", 826, 2)
const GEL = Currency("GEL", "Lari", "", 981, 2)
const GHS = Currency("GHS", "Ghana Cedi", "GH₵", 936, 2)
const GIP = Currency("GIP", "Gibraltar Pound", "", 292, 2)
const GMD = Currency("GMD", "Dalasi", "", 270, 2)
const GNF = Currency("GNF", "Guinean Franc", "", 324, 0)
const GTQ = Currency("GTQ", "Quetzal", "Q", 320, 2)
const GYD = Currency("GYD", "Guyana Dollar", "", 328, 2)
const HKD = Currency("HKD", "Hong Kong Dollar", "\$", 344, 2)
const HNL = Currency("HNL", "Lempira", "L", 340, 2)
const HRK = Currency("HRK", "Kuna", "kn", 191, 2)
const HTG = Currency("HTG", "Gourde", "", 332, 2)
const HUF = Currency("HUF", "Forint", "Ft", 348, 2)
const IDR = Currency("IDR", "Rupiah", "Rp", 360, 2)
const ILS = Currency("ILS", "New Israeli Sheqel", "₪", 376, 2)
const INR = Currency("INR", "Indian Rupee", "₹", 356, 2)
const IQD = Currency("IQD", "Iraqi Dinar", "", 368, 3)
const IRR = Currency("IRR", "Iranian Rial", "", 364, 2)
const ISK = Currency("ISK", "Iceland Krona", "kr", 352, 0)
const JMD = Currency("JMD", "Jamaican Dollar", "J\$", 388, 2)
const JOD = Currency("JOD", "Jordanian Dinar", "", 400, 3)
const JPY = Currency("JPY", "Yen", "¥", 392, 0)
const KES = Currency("KES", "Kenyan Shilling", "", 404, 2)
const KGS = Currency("KGS", "Som", "", 417, 2)
const KHR = Currency("KHR", "Riel", "", 116, 2)
const KMF = Currency("KMF", "Comorian Franc ", "", 174, 0)
const KPW = Currency("KPW", "North Korean Won", "", 408, 2)
const KRW = Currency("KRW", "Won", "₩", 410, 0)
const KWD = Currency("KWD", "Kuwaiti Dinar", "", 414, 3)
const KYD = Currency("KYD", "Cayman Islands Dollar", "", 136, 2)
const KZT = Currency("KZT", "Tenge", "", 398, 2)
const LAK = Currency("LAK", "Lao Kip", "", 418, 2)
const LBP = Currency("LBP", "Lebanese Pound", "", 422, 2)
const LKR = Currency("LKR", "Sri Lanka Rupee", "₨", 144, 2)
const LRD = Currency("LRD", "Liberian Dollar", "", 430, 2)
const LSL = Currency("LSL", "Loti", "", 426, 2)
const LYD = Currency("LYD", "Libyan Dinar", "", 434, 3)
const MAD = Currency("MAD", "Moroccan Dirham", ".د.م", 504, 2)
const MDL = Currency("MDL", "Moldovan Leu", "", 498, 2)
const MGA = Currency("MGA", "Malagasy Ariary", "", 969, 2)
const MKD = Currency("MKD", "Denar", "", 807, 2)
const MMK = Currency("MMK", "Kyat", "K", 104, 2)
const MNT = Currency("MNT", "Tugrik", "", 496, 2)
const MOP = Currency("MOP", "Pataca", "", 446, 2)
const MRU = Currency("MRU", "Ouguiya", "", 929, 2)
const MUR = Currency("MUR", "Mauritius Rupee", "", 480, 2)
const MVR = Currency("MVR", "Rufiyaa", "", 462, 2)
const MWK = Currency("MWK", "Malawi Kwacha", "", 454, 2)
const MXN = Currency("MXN", "Mexican Peso", "\$", 484, 2)
const MXV = Currency("MXV", "Mexican Unidad de Inversion (UDI)", "", 979, 2)
const MYR = Currency("MYR", "Malaysian Ringgit", "RM", 458, 2)
const MZN = Currency("MZN", "Mozambique Metical", "", 943, 2)
const NAD = Currency("NAD", "Namibia Dollar", "", 516, 2)
const NGN = Currency("NGN", "Naira", "", 566, 2)
const NIO = Currency("NIO", "Cordoba Oro", "", 558, 2)
const NOK = Currency("NOK", "Norwegian Krone", "kr", 578, 2)
const NPR = Currency("NPR", "Nepalese Rupee", "", 524, 2)
const NZD = Currency("NZD", "New Zealand Dollar", "\$", 554, 2)
const OMR = Currency("OMR", "Rial Omani", "", 512, 3)
const PAB = Currency("PAB", "Balboa", "B/.", 590, 2)
const PEN = Currency("PEN", "Sol", "S/.", 604, 2)
const PGK = Currency("PGK", "Kina", "", 598, 2)
const PHP = Currency("PHP", "Philippine Peso", "₱", 608, 2)
const PKR = Currency("PKR", "Pakistan Rupee", "₨", 586, 2)
const PLN = Currency("PLN", "Zloty", "zł", 985, 2)
const PYG = Currency("PYG", "Guarani", "", 600, 0)
const QAR = Currency("QAR", "Qatari Rial", "", 634, 2)
const RON = Currency("RON", "Romanian Leu", "lei", 946, 2)
const RSD = Currency("RSD", "Serbian Dinar", "RSD", 941, 2)
const RUB = Currency("RUB", "Russian Ruble", "руб", 643, 2)
const RWF = Currency("RWF", "Rwanda Franc", "", 646, 0)
const SAR = Currency("SAR", "Saudi Riyal", "", 682, 2)
const SBD = Currency("SBD", "Solomon Islands Dollar", "", 90, 2)
const SCR = Currency("SCR", "Seychelles Rupee", "", 690, 2)
const SDG = Currency("SDG", "Sudanese Pound", "", 938, 2)
const SEK = Currency("SEK", "Swedish Krona", "kr", 752, 2)
const SGD = Currency("SGD", "Singapore Dollar", "S\$", 702, 2)
const SHP = Currency("SHP", "Saint Helena Pound", "", 654, 2)
const SLL = Currency("SLL", "Leone", "", 694, 2)
const SOS = Currency("SOS", "Somali Shilling", "", 706, 2)
const SRD = Currency("SRD", "Surinam Dollar", "", 968, 2)
const SSP = Currency("SSP", "South Sudanese Pound", "", 728, 2)
const STN = Currency("STN", "Dobra", "", 930, 2)
const SVC = Currency("SVC", "El Salvador Colon", "", 222, 2)
const SYP = Currency("SYP", "Syrian Pound", "", 760, 2)
const SZL = Currency("SZL", "Lilangeni", "", 748, 2)
const THB = Currency("THB", "Baht", "฿", 764, 2)
const TJS = Currency("TJS", "Somoni", "", 972, 2)
const TMT = Currency("TMT", "Turkmenistan New Manat", "", 934, 2)
const TND = Currency("TND", "Tunisian Dinar", "DT", 788, 3)
const TOP = Currency("TOP", "Pa’anga", "", 776, 2)
const TRY = Currency("TRY", "Turkish Lira", "TL", 949, 2)
const TTD = Currency("TTD", "Trinidad and Tobago Dollar", "\$", 780, 2)
const TWD = Currency("TWD", "New Taiwan Dollar", "NT\$", 901, 2)
const TZS = Currency("TZS", "Tanzanian Shilling", "", 834, 2)
const UAH = Currency("UAH", "Hryvnia", "", 980, 2)
const UGX = Currency("UGX", "Uganda Shilling", "", 800, 0)
const USD = Currency("USD", "US Dollar", "\$", 840, 2)
const USN = Currency("USN", "US Dollar (Next day)", "", 997, 2)
const UYI = Currency("UYI", "Uruguay Peso en Unidades Indexadas (UI)", "", 940, 0)
const UYU = Currency("UYU", "Peso Uruguayo", "", 858, 2)
const UYW = Currency("UYW", "Unidad Previsional", "", 927, 4)
const UZS = Currency("UZS", "Uzbekistan Sum", "", 860, 2)
const VED = Currency("VED", "Bolívar Soberano", "", 926, 2)
const VES = Currency("VES", "Bolívar Soberano", "", 928, 2)
const VND = Currency("VND", "Dong", "₫", 704, 0)
const VUV = Currency("VUV", "Vatu", "", 548, 0)
const WST = Currency("WST", "Tala", "", 882, 2)
const XAF = Currency("XAF", "CFA Franc BEAC", "FCFA", 950, 0)
const XAG = Currency("XAG", "Silver", "", 961, -1)
const XAU = Currency("XAU", "Gold", "", 959, -1)
const XBA = Currency("XBA", "Bond Markets Unit European Composite Unit (EURCO)", "", 955, -1)
const XBB = Currency("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "", 956, -1)
const XBC = Currency("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "", 957, -1)
const XBD = Currency("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "", 958, -1)
const XCD = Currency("XCD", "East Caribbean Dollar", "\$", 951, 2)
const XDR = Currency("XDR", "SDR (Special Drawing Right)", "", 960, -1)
const XOF = Currency("XOF", "CFA Franc BCEAO", "", 952, 0)
const XPD = Currency("XPD", "Palladium", "", 964, -1)
const XPF = Currency("XPF", "CFP Franc", "F", 953, 0)
const XPT = Currency("XPT", "Platinum", "", 962, -1)
const XSU = Currency("XSU", "Sucre", "", 994, -1)
const XTS = Currency("XTS", "Codes specifically reserved for testing purposes", "", 963, -1)
const XUA = Currency("XUA", "ADB Unit of Account", "", 965, -1)
const XXX = Currency("XXX", "The codes assigned for transactions where no currency is involved", "", 999, -1)
const YER = Currency("YER", "Yemeni Rial", "", 886, 2)
const ZAR = Currency("ZAR", "Rand", "R", 710, 2)
const ZMW = Currency("ZMW", "Zambian Kwacha", "", 967, 2)
const ZWL = Currency("ZWL", "Zimbabwe Dollar", "", 932, 2)

const CURRENCIES = Currency[
    AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, 
    BOB, BOV, BRL, BSD, BTN, BWP, BYN, BZD, CAD, CDF, CHE, CHF, CHW, CLF, CLP, CNY, COP, COU, 
    CRC, CUC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GEL, GHS, 
    GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, INR, IQD, IRR, ISK, JMD, JOD, 
    JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, 
    MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR, MWK, MXN, MXV, MYR, MZN, NAD, NGN, NIO, NOK, NPR, 
    NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, 
    SEK, SGD, SHP, SLL, SOS, SRD, SSP, STN, SVC, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, 
    TWD, TZS, UAH, UGX, USD, USN, UYI, UYU, UYW, UZS, VED, VES, VND, VUV, WST, XAF, XAG, XAU, 
    XBA, XBB, XBC, XBD, XCD, XDR, XOF, XPD, XPF, XPT, XSU, XTS, XUA, XXX, YER, ZAR, ZMW, ZWL, ]

const COUNTRIES = Dict(
    "AFGHANISTAN" => [AFN],
    "ALBANIA" => [ALL],
    "ALGERIA" => [DZD],
    "AMERICAN SAMOA" => [USD],
    "ANDORRA" => [EUR],
    "ANGOLA" => [AOA],
    "ANGUILLA" => [XCD],
    "ANTARCTICA" => [],
    "ANTIGUA AND BARBUDA" => [XCD],
    "ARGENTINA" => [ARS],
    "ARMENIA" => [AMD],
    "ARUBA" => [AWG],
    "AUSTRALIA" => [AUD],
    "AUSTRIA" => [EUR],
    "AZERBAIJAN" => [AZN],
    "BAHAMAS (THE)" => [BSD],
    "BAHRAIN" => [BHD],
    "BANGLADESH" => [BDT],
    "BARBADOS" => [BBD],
    "BELARUS" => [BYN],
    "BELGIUM" => [EUR],
    "BELIZE" => [BZD],
    "BENIN" => [XOF],
    "BERMUDA" => [BMD],
    "BHUTAN" => [INR, BTN],
    "BOLIVIA (PLURINATIONAL STATE OF)" => [BOB, BOV],
    "BONAIRE, SINT EUSTATIUS AND SABA" => [USD],
    "BOSNIA AND HERZEGOVINA" => [BAM],
    "BOTSWANA" => [BWP],
    "BOUVET ISLAND" => [NOK],
    "BRAZIL" => [BRL],
    "BRITISH INDIAN OCEAN TERRITORY (THE)" => [USD],
    "BRUNEI DARUSSALAM" => [BND],
    "BULGARIA" => [BGN],
    "BURKINA FASO" => [XOF],
    "BURUNDI" => [BIF],
    "CABO VERDE" => [CVE],
    "CAMBODIA" => [KHR],
    "CAMEROON" => [XAF],
    "CANADA" => [CAD],
    "CAYMAN ISLANDS (THE)" => [KYD],
    "CENTRAL AFRICAN REPUBLIC (THE)" => [XAF],
    "CHAD" => [XAF],
    "CHILE" => [CLP, CLF],
    "CHINA" => [CNY],
    "CHRISTMAS ISLAND" => [AUD],
    "COCOS (KEELING) ISLANDS (THE)" => [AUD],
    "COLOMBIA" => [COP, COU],
    "COMOROS (THE)" => [KMF],
    "CONGO (THE DEMOCRATIC REPUBLIC OF THE)" => [CDF],
    "CONGO (THE)" => [XAF],
    "COOK ISLANDS (THE)" => [NZD],
    "COSTA RICA" => [CRC],
    "CROATIA" => [HRK],
    "CUBA" => [CUP, CUC],
    "CURAÇAO" => [ANG],
    "CYPRUS" => [EUR],
    "CZECHIA" => [CZK],
    "CÔTE D'IVOIRE" => [XOF],
    "DENMARK" => [DKK],
    "DJIBOUTI" => [DJF],
    "DOMINICA" => [XCD],
    "DOMINICAN REPUBLIC (THE)" => [DOP],
    "ECUADOR" => [USD],
    "EGYPT" => [EGP],
    "EL SALVADOR" => [SVC, USD],
    "EQUATORIAL GUINEA" => [XAF],
    "ERITREA" => [ERN],
    "ESTONIA" => [EUR],
    "ESWATINI" => [SZL],
    "ETHIOPIA" => [ETB],
    "EUROPEAN UNION" => [EUR],
    "FALKLAND ISLANDS (THE) [MALVINAS]" => [FKP],
    "FAROE ISLANDS (THE)" => [DKK],
    "FIJI" => [FJD],
    "FINLAND" => [EUR],
    "FRANCE" => [EUR],
    "FRENCH GUIANA" => [EUR],
    "FRENCH POLYNESIA" => [XPF],
    "FRENCH SOUTHERN TERRITORIES (THE)" => [EUR],
    "GABON" => [XAF],
    "GAMBIA (THE)" => [GMD],
    "GEORGIA" => [GEL],
    "GERMANY" => [EUR],
    "GHANA" => [GHS],
    "GIBRALTAR" => [GIP],
    "GREECE" => [EUR],
    "GREENLAND" => [DKK],
    "GRENADA" => [XCD],
    "GUADELOUPE" => [EUR],
    "GUAM" => [USD],
    "GUATEMALA" => [GTQ],
    "GUERNSEY" => [GBP],
    "GUINEA" => [GNF],
    "GUINEA-BISSAU" => [XOF],
    "GUYANA" => [GYD],
    "HAITI" => [HTG, USD],
    "HEARD ISLAND AND McDONALD ISLANDS" => [AUD],
    "HOLY SEE (THE)" => [EUR],
    "HONDURAS" => [HNL],
    "HONG KONG" => [HKD],
    "HUNGARY" => [HUF],
    "ICELAND" => [ISK],
    "INDIA" => [INR],
    "INDONESIA" => [IDR],
    "INTERNATIONAL MONETARY FUND (IMF) " => [XDR],
    "IRAN (ISLAMIC REPUBLIC OF)" => [IRR],
    "IRAQ" => [IQD],
    "IRELAND" => [EUR],
    "ISLE OF MAN" => [GBP],
    "ISRAEL" => [ILS],
    "ITALY" => [EUR],
    "JAMAICA" => [JMD],
    "JAPAN" => [JPY],
    "JERSEY" => [GBP],
    "JORDAN" => [JOD],
    "KAZAKHSTAN" => [KZT],
    "KENYA" => [KES],
    "KIRIBATI" => [AUD],
    "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)" => [KPW],
    "KOREA (THE REPUBLIC OF)" => [KRW],
    "KUWAIT" => [KWD],
    "KYRGYZSTAN" => [KGS],
    "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)" => [LAK],
    "LATVIA" => [EUR],
    "LEBANON" => [LBP],
    "LESOTHO" => [LSL, ZAR],
    "LIBERIA" => [LRD],
    "LIBYA" => [LYD],
    "LIECHTENSTEIN" => [CHF],
    "LITHUANIA" => [EUR],
    "LUXEMBOURG" => [EUR],
    "MACAO" => [MOP],
    "MADAGASCAR" => [MGA],
    "MALAWI" => [MWK],
    "MALAYSIA" => [MYR],
    "MALDIVES" => [MVR],
    "MALI" => [XOF],
    "MALTA" => [EUR],
    "MARSHALL ISLANDS (THE)" => [USD],
    "MARTINIQUE" => [EUR],
    "MAURITANIA" => [MRU],
    "MAURITIUS" => [MUR],
    "MAYOTTE" => [EUR],
    "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP" => [XUA],
    "MEXICO" => [MXN, MXV],
    "MICRONESIA (FEDERATED STATES OF)" => [USD],
    "MOLDOVA (THE REPUBLIC OF)" => [MDL],
    "MONACO" => [EUR],
    "MONGOLIA" => [MNT],
    "MONTENEGRO" => [EUR],
    "MONTSERRAT" => [XCD],
    "MOROCCO" => [MAD],
    "MOZAMBIQUE" => [MZN],
    "MYANMAR" => [MMK],
    "NAMIBIA" => [NAD, ZAR],
    "NAURU" => [AUD],
    "NEPAL" => [NPR],
    "NETHERLANDS (THE)" => [EUR],
    "NEW CALEDONIA" => [XPF],
    "NEW ZEALAND" => [NZD],
    "NICARAGUA" => [NIO],
    "NIGER (THE)" => [XOF],
    "NIGERIA" => [NGN],
    "NIUE" => [NZD],
    "NORFOLK ISLAND" => [AUD],
    "NORTH MACEDONIA" => [MKD],
    "NORTHERN MARIANA ISLANDS (THE)" => [USD],
    "NORWAY" => [NOK],
    "OMAN" => [OMR],
    "PAKISTAN" => [PKR],
    "PALAU" => [USD],
    "PALESTINE, STATE OF" => [],
    "PANAMA" => [PAB, USD],
    "PAPUA NEW GUINEA" => [PGK],
    "PARAGUAY" => [PYG],
    "PERU" => [PEN],
    "PHILIPPINES (THE)" => [PHP],
    "PITCAIRN" => [NZD],
    "POLAND" => [PLN],
    "PORTUGAL" => [EUR],
    "PUERTO RICO" => [USD],
    "QATAR" => [QAR],
    "ROMANIA" => [RON],
    "RUSSIAN FEDERATION (THE)" => [RUB],
    "RWANDA" => [RWF],
    "RÉUNION" => [EUR],
    "SAINT BARTHÉLEMY" => [EUR],
    "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" => [SHP],
    "SAINT KITTS AND NEVIS" => [XCD],
    "SAINT LUCIA" => [XCD],
    "SAINT MARTIN (FRENCH PART)" => [EUR],
    "SAINT PIERRE AND MIQUELON" => [EUR],
    "SAINT VINCENT AND THE GRENADINES" => [XCD],
    "SAMOA" => [WST],
    "SAN MARINO" => [EUR],
    "SAO TOME AND PRINCIPE" => [STN],
    "SAUDI ARABIA" => [SAR],
    "SENEGAL" => [XOF],
    "SERBIA" => [RSD],
    "SEYCHELLES" => [SCR],
    "SIERRA LEONE" => [SLL],
    "SINGAPORE" => [SGD],
    "SINT MAARTEN (DUTCH PART)" => [ANG],
    "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \"SUCRE\"" => [XSU],
    "SLOVAKIA" => [EUR],
    "SLOVENIA" => [EUR],
    "SOLOMON ISLANDS" => [SBD],
    "SOMALIA" => [SOS],
    "SOUTH AFRICA" => [ZAR],
    "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" => [],
    "SOUTH SUDAN" => [SSP],
    "SPAIN" => [EUR],
    "SRI LANKA" => [LKR],
    "SUDAN (THE)" => [SDG],
    "SURINAME" => [SRD],
    "SVALBARD AND JAN MAYEN" => [NOK],
    "SWEDEN" => [SEK],
    "SWITZERLAND" => [CHF, CHE, CHW],
    "SYRIAN ARAB REPUBLIC" => [SYP],
    "TAIWAN (PROVINCE OF CHINA)" => [TWD],
    "TAJIKISTAN" => [TJS],
    "TANZANIA, UNITED REPUBLIC OF" => [TZS],
    "THAILAND" => [THB],
    "TIMOR-LESTE" => [USD],
    "TOGO" => [XOF],
    "TOKELAU" => [NZD],
    "TONGA" => [TOP],
    "TRINIDAD AND TOBAGO" => [TTD],
    "TUNISIA" => [TND],
    "TURKEY" => [TRY],
    "TURKMENISTAN" => [TMT],
    "TURKS AND CAICOS ISLANDS (THE)" => [USD],
    "TUVALU" => [AUD],
    "UGANDA" => [UGX],
    "UKRAINE" => [UAH],
    "UNITED ARAB EMIRATES (THE)" => [AED],
    "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)" => [GBP],
    "UNITED STATES MINOR OUTLYING ISLANDS (THE)" => [USD],
    "UNITED STATES OF AMERICA (THE)" => [USD, USN],
    "URUGUAY" => [UYU, UYI, UYW],
    "UZBEKISTAN" => [UZS],
    "VANUATU" => [VUV],
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)" => [VES, VED],
    "VIET NAM" => [VND],
    "VIRGIN ISLANDS (BRITISH)" => [USD],
    "VIRGIN ISLANDS (U.S.)" => [USD],
    "WALLIS AND FUTUNA" => [XPF],
    "WESTERN SAHARA" => [MAD],
    "YEMEN" => [YER],
    "ZAMBIA" => [ZMW],
    "ZIMBABWE" => [ZWL],
    "ZZ01_Bond Markets Unit European_EURCO" => [XBA],
    "ZZ02_Bond Markets Unit European_EMU-6" => [XBB],
    "ZZ03_Bond Markets Unit European_EUA-9" => [XBC],
    "ZZ04_Bond Markets Unit European_EUA-17" => [XBD],
    "ZZ06_Testing_Code" => [XTS],
    "ZZ07_No_Currency" => [XXX],
    "ZZ08_Gold" => [XAU],
    "ZZ09_Palladium" => [XPD],
    "ZZ10_Platinum" => [XPT],
    "ZZ11_Silver" => [XAG],
    "ÅLAND ISLANDS" => [EUR],
)
